Save testbed configuration in directory with testbed's name
- aws-setup saves description file to testbed/testbed.desc
- node-setup requires testbed name as argument, and testbed description file
  unless provided with -f
- Find SSH key file and copy it to testbed directory
- Add usage() to node-setup, rename -i to -n in aws-setup

diff --git a/node-setup b/node-setup
--- a/node-setup
+++ b/node-setup
@@ -5,8 +5,8 @@
 #
 
 # kill children if script was interrupted
-trap 'echo killing ${pids[@]}; kill ${pids[@]}' SIGTERM
-trap 'echo killing ${pids[@]}; kill ${pids[@]}' SIGINT
+trap 'kill ${pids[@]} 2>/dev/null' SIGTERM
+trap 'kill ${pids[@]} 2>/dev/null' SIGINT
 
 # Color escape codes
 RESTORE='\033[0m'
@@ -14,57 +14,80 @@ RED='\033[00;31m'
 GREEN='\033[00;32m'
 YELLOW='\033[00;33m'
 
-
 msg() {
     case "$1" in
-        error)  echo -ne "$RED"                 >&2
-                echo "$0 ${@:2}"     >&2
+        error)  echo -ne "$RED"     >&2
+                echo "$0: ${@:2}"    >&2
+                exit 1
                 ;;
-        warn)   echo -ne "$YELLOW"              >&2
-                echo "$0 ${@:2}"     >&2
+        warn)   echo -ne "$YELLOW"  >&2
+                echo "$0: ${@:2}"    >&2
                 ;;
         *)      echo -ne "$GREEN"
-                echo "$0 ${@}"
+                echo "$0: ${@}"
     esac
 
     # restore normal colors
     echo -ne "$restore"
-    echo -ne "$restore"    >&2
+    echo -ne "$restore" >&2
 }
 
 usage() {
+    # print to stderr
     exec 5>&1
     exec 1>&2
-    echo "Usage: $0 [options] DESCFILE"
+    echo "Usage: (-h for more information)"
+    echo "$0 [[-f DESCFILE] | [-n -i IP -h HOSTNAME -c CONTROLLER_IP -n CONTROLLER_HOSTNAME -k SSH_KEY]] TESTBED"
+    # restore stdout
+    exec 0>&5
+}
+
+help() {
+    # print to stderr
+    exec 5>&1
+    exec 1>&2
+    echo "Usage: $0 [options] TESTBED"
     echo ""
-    echo "DESCFILE describes the testbed in key=value format."
+    echo "TESTBED is the name of the set of machines where OpenStack will be installed."
+    echo ""
     echo "Options:"
+    echo "-f DESCFILE, --file DESCFILE"
+    echo "                      Description of the tesbed with entries in key=value format"
+    echo "                      default: TESTBED/TESTBED.desc"
+    echo "-n, --node"
+    echo "                      Configure from command-line instead of using a description file"
+    echo "-k KEY, --key KEY"
+    echo "                      Name of SSH key to use"
+    echo "                      default: openstack"
     echo "-i IP, --ip IP"
     echo "                      Node IP address"
     echo "-h HOSTNAME, --hostname HOSTNAME"
     echo "                      Node hostname"
-    echo "-c CONTROLLER_IP, --controller_ip CONTROLLER_IP"
+    echo "-c IP, --controller_ip IP"
     echo "                      Controller IP address"
-    echo "-n CONTROLLER_HOSTNAME, --controller_hostname CONTROLLER_HOSTNAME"
+    echo "-t HOSTNAME, --controller_hostname HOSTNAME"
     echo "                      Controller hostname"
-    echo "-k SSH_KEY, --key SSH_KEY"
-    echo "                      Name of SSH key to use"
+    echo "-v, --verbose"
+    echo "                      Show verbose progress"
     echo ""
     echo "Example:"
-    echo "$0 openstack.desc"
-    echo "   This command will read testbed description from openstack.desc and configure the nodes accordingly."
+    echo "$0 openstack"
+    echo "   This command will read testbed description from openstack.desc"
+    echo "   (or openstack/openstack.desc) and configure the nodes accordingly."
     echo ""
-    echo "$0 -i 10.0.0.5 -h compute1.ec2.internal -c 10.0.0.1 -n controller.ec2.internal"
-    echo "   This command will connect to 10.0.0.5 and configure it as a compute node with controller 10.0.0.1"
+    echo "$0 -i 10.0.0.5 -h compute1.ec2.internal -c 10.0.0.1 controller.ec2.internal"
+    echo "   This command will connect to 10.0.0.5 and configure it as a compute"
+    echo "   node with controller 10.0.0.1"
     echo ""
     echo "Notes:"
     echo "This tool will use the following values from DESCFILE:"
     echo " ssh_key, controller.elastic_ip, controller_private_ip, compute*_private_ip"
     echo ""
+    # restore stdout
     exec 1>&5
 }
 
-ARGS=$(getopt -o "hi:h:c:n:k:" -l "help,ip:,hostname:,controller_ip:,controller_hostname:,key:" -n "$0" -- "$@")
+ARGS=$(getopt -o "hf:i:h:c:vn" -l "help,file:,ip:,hostname:,controller_ip:,controller_hostname:,key:,verbose,node" -n "$0" -- "$@")
 
 if [ $? != 0 ] ; then
     msg error "error parsing command-line options"
@@ -76,26 +99,33 @@ eval set -- "$ARGS"
 while true; do
     case "$1" in
         -h|--help)
-            usage
+            help
             exit 0
             shift;;
+        -f|--file)
+            testbed_file=$2
+            shift 2;;
         -i|--ip)
             node_ip=$2
             shift 2;;
         -h|--hostname)
             node_hostname=$2
             shift 2;;
-        -c|--controller_ip)
+        --controller_ip)
             controller_ip=$2
             shift 2;;
-        -n|--controller_hostname)
+        --controller_hostname)
             controller_hostname=$2
             shift 2;;
+        -n|--node)
+            node=1
+            shift;;
         -k|--key)
             ssh_key=$2
             shift 2;;
         -v|--verbose)
-            options_verbose=1
+            verbose="-v"
+            set -x
             shift;;
         --)
             shift
@@ -127,52 +157,59 @@ parsedesc() {
 
 configure_controller() {
     scp $ssh_opts "${files[@]}" $ssh_dst: &>/dev/null
-    ssh $ssh_opts $ssh_dst "sudo bash masquerade" &>/dev/null
+    ssh $ssh_opts $ssh_dst "sudo bash masquerade 2>/dev/null"
     ssh $ssh_opts $ssh_dst "sudo bash puppet-openstack-configure -h $controller_hostname $controller_hostname $controller_ip"
-    scp $ssh_opts $ssh_dst:$controller_hostname.log .
+    scp $ssh_opts $ssh_dst:$controller_hostname.log $testbed
 }
 
 configure_node() {
-    scp -v $ssh_opts "${files[@]}" $ssh_dst: &>/dev/null
-    ssh $ssh_opts $ssh_dst "sudo ip ro d default; sudo ip ro a default via $controller_ip" &>/dev/null
+    scp $ssh_opts "${files[@]}" $ssh_dst: &>/dev/null
+    ssh $ssh_opts $ssh_dst "sudo ip ro d default; sudo ip ro a default via $controller_ip" 2>/dev/null
     ssh $ssh_opts $ssh_dst "sudo bash puppet-openstack-configure -h $node_hostname $controller_hostname $controller_ip"
     scp $ssh_opts $ssh_dst:$node_hostname.log .
 }
 
-testbed_file=$1
-testbed=${testbed_file%.*}
-testbed=${testbed##*/}
-
+# global variables
 user=ubuntu
 files=(puppet-openstack-configure site.pp node-setup masquerade)
 ssh_opts="-qo UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
 declare -a pids
 
-# we can configure a testbed description file or a specific node
-if [[ -n $testbed ]]; then
-    if [[ -n $node_ip ]]; then
-        msg error "Script can configure a testbed (from a description file) or a node, but not both"
-        msg error "type $0 -h for usage"
-        exit 1
-    fi
+# if testbed file wasn't specified in the command-line,
+# try to find it in the $testbed directory
+if (($#!=1)); then
+    usage
+    exit 1
+fi
+
+testbed=$1
+[[ -z $testbed_file ]] && testbed_file=$1/$1.desc
+
+if [[ -z $testbed ]]; then
+    testbed=${testbed_file%.*}
+    testbed=${testbed##*/}
+fi
+
+# configuring testbed from description file
+if [[ -z $node ]]; then
+
+    [[ ! -e $testbed_file ]] && msg error "$testbed_file not found"
+
     declare -a hosts
     parsedesc $testbed_file
 
+    # try to find ssh key in current directory, "testbed", "keys"
     basedir=$(dirname $testbed_file)
-    if [ -f $basedir/$ssh_key.pem ]; then
-        ssh_key_file=$dir/$ssh_key.pem
-    elif [ -f $testbed/$ssh_key.pem ] ; then
-        ssh_key_file=$testbed/$ssh_key.pem 
-    elif [ -f keys/$ssh_key.pem ]; then
-        ssh_key_file=keys/$ssh_key.pem
-    else
-        msg error "Could not find SSH key: $ssh_key"
-        exit 1
-    fi
+    for dir in $basedir $testbed keys; do
+        if [ -f $dir/$ssh_key.pem ]; then
+            ssh_key_file=$dir/$ssh_key.pem
+            break
+        fi
+    done
+    [[ -f $ssh_key_file ]] || msg error "Could not find SSH key: $ssh_key"
 
-
-    msg "Using Elastic IP: $elastic_ip"
-    msg "Configuring controller: $controller_hostname ($controller_ip)"
+    msg "Connecting to $elastic_ip"
+    msg "Configuring: $controller_hostname ($controller_ip)"
 
     ssh_opts+=" -i $ssh_key_file"
     files+=($ssh_key_file)
@@ -180,7 +217,12 @@ if [[ -n $testbed ]]; then
 
     # Configure controller by connecting via ssh and running
     # puppet-openstack-configure
-    { configure_controller && msg "Successfully configured controller" || msg error "Error configuring controller"; } &
+    { if configure_controller; then
+            msg "Successfully configured $controller_hostname"
+        else
+            msg error "Error configuring $controller_hostname"
+        fi
+    } & # run in the background
     pids+=($!)
 
     # wait until Puppet server is configured to start setting up compute nodes
@@ -191,16 +233,31 @@ if [[ -n $testbed ]]; then
     # Configure compute nodes by recursively calling this script from the
     # controller passing --node, the controller host/ip and the node's internal
     # ip
-    i=0
+    ((i=0))
     for node_hostname in ${hosts[@]}; do
         node_ip=${ips[$i]}
-        msg "Configuring node: $node_hostname ($node_ip)"
-        ssh $ssh_opts $ssh_dst "sudo bash node-setup --ip $node_ip --hostname $node_hostname --controller_ip $controller_ip --controller_hostname $controller_hostname --key $ssh_key" &
+        msg "Configuring: $node_hostname ($node_ip)"
+        ssh $ssh_opts $ssh_dst "sudo bash $0 $verbose --node --ip $node_ip --hostname $node_hostname --controller_ip $controller_ip --controller_hostname $controller_hostname --key $ssh_key $testbed" &
         pids+=($!)
-        i+=1
+        ((i+=1))
     done
 
-elif [[ -n $node_ip && -n $node_hostname && -n $controller_ip && -n $controller_hostname && -n $ssh_key.pem ]]; then
+    wait
+
+    if curl -s "http://${elastic_ip}/horizon" | grep -q Dashboard; then
+        msg "Setup complete. Dashboard: http://${elastic_ip}/horizon"
+    fi
+
+    scp $ssh_opts $ssh_dst:$testbed-compute*.log $testbed
+
+# configuring node (called recursively from this script)
+else
+    if [[ -z $node_ip || -z $node_hostname || -z $controller_ip || \
+      -z $controller_hostname || -z $ssh_key ]]; then
+        usage
+        exit 1
+    fi
+
     ssh_opts+=" -i $ssh_key.pem"
     ssh_dst="$user@$node_ip"
     { if configure_node; then
@@ -208,15 +265,9 @@ elif [[ -n $node_ip && -n $node_hostname && -n $controller_ip && -n $controller_
     else
         msg error "Error configuring $node_hostname";
     fi
-    scp $ssh_opts $ssh_dst:$node_hostname.log .
+    scp $ssh_opts $ssh_dst:$node_hostname.log $testbed
     } &
     pids+=($!)
-else
-    usage
-    exit 1
+    wait
 fi
-
-
-# otherwise wait for them to configure nodes
-wait
 
