Ensure databases are set up before configuring compute nodes

diff --git a/puppet-openstack-configure b/puppet-openstack-configure
--- a/puppet-openstack-configure
+++ b/puppet-openstack-configure
@@ -54,8 +54,8 @@ usage() {
 
 installpkg() {
     if ! dpkg -s $1 &>/dev/null; then
-        msg "Installing: $1"
-        runcmd aptitude -y install $@
+        [[ $2 == silent ]] || msg "Installing: $1"
+        runcmd aptitude -y install $1
     fi
 }
 
@@ -178,6 +178,7 @@ configure_puppetmaster() {
     echo -e '*.local\n*.internal' > /etc/puppet/autosign.conf
 }
 
+
 if ((UID!=0)); then
     msg error "This script needs to be run as root"
     exit 1
@@ -272,7 +273,22 @@ else
         sudo rm /var/lib/puppet/state/agent_catalog_run.lock 2>/dev/null
     fi
 fi
-msg "Installing and configuring: OpenStack"
+
+# wait until mysql is installed to run puppet agent, otherwise nova
+# services won't start
+if [[ $hostname != $controller_hostname ]]; then
+    ((i=0))
+    installpkg mysql-client silent
+    while ! mysql -u nova -pnova_pass -h $controller_ip nova <<< "show databases" &>/dev/null; do
+        sleep 5
+        i+=1
+        if ((i==10)); then
+            msg error "Could not connect to mysql server on $controller_ip"
+        fi
+    done
+fi
+
+msg "Installing and configuring OpenStack"
 runcmd puppet agent -t
 
 # puppet agent will return 2 while parsing /etc/nova/nova.conf
